version: 2.1

orbs:
  codecov: codecov/codecov@1.0.3

jobs:
  build:
    working_directory: ~/repo

    docker: 
      - image: circleci/node:8

    steps:
      - checkout
      
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache: 
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn 
            
  test:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run: yarn test
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
